### ISSUE TITLE
调用当前应用变成小窗

### ISSUE THREAD

**Issue by bigm0re** [eswd04/freeform_update#1]
不知道能不能重新实现，原版的2.0.5可以用shell来打开的，之前的实现代码如下
am broadcast -a com.sunshine.freeform.start_by_mi_freeform -p com.sunshine.freeform --es packageName $(dumpsys window | grep mCurrentFocus | awk '{print $3}'|cut -f 1 -d "/") --es activityName $(dumpsys window | grep mCurrentFocus | awk '{print $3}'|cut -f 1 -d "}")

**Comment by eswd04** [comment]
虽然说可以实现，但是……我这边打算几天上传稳定支持Android10的版本后，暂时就不打算继续更新了。因此建议你等待官方版本的后续更新:yum:

**Comment by eswd04** [comment]
@bigm0re 虽然说可以实现，但是……我这边打算几天上传稳定支持Android10的版本后，暂时就不打算继续更新了。因此建议你等待官方版本的后续更新:yum:

**Comment by bigm0re** [comment]
OK，官方2.0.5后的版本也没有这个调用方式了，看样子是没有办法了

**Comment by eswd04** [comment]
@bigm0re 下版本更新：
示例:
adb shell am broadcast -a com.sunshine.freeform.start_notification_app --es package "com.tencent.tim" com.sunshine.freeform
