### ISSUE TITLE
不识别Xposed

### ISSUE THREAD

**Issue by ghost** [eswd04/freeform_update#5]
LSPosed已经给米窗勾选了系统框架，但是米窗应用里却显示Xposed没勾选系统框架

**Comment by ghost** [comment]
![Screenshot_20230409-142554_LSPosed](https://user-images.githubusercontent.com/120433823/230758609-3747fda5-1f00-495a-97f8-68b501d7f0b5.png)

**Comment by mini-three** [comment]
![Uploading Screenshot_20230409-142604_米窗-全局小窗.png…]()

**Comment by eswd04** [comment]
正常情况下，勾选系统框架后需要重启设备

**Comment by eswd04** [comment]
问题未更新提供反馈，因此关闭此单
